site_name: "🔐 Programació, Xarxes i Sistemes Informàtics II — 2n Batxillerat"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Introducció a Python":
      - "📘 UD1 Completa (1 pàgina)": ut00/index.md
      - "1.1 Introducció a Python": ut00/ut0001.md
      - "1.2 Elementos de un programa": ut00/ut0002.md
      - "1.3 Tipos de datos": ut00/ut0003.md
      - "1.4 Funciones integradas": ut00/ut0004.md
      - "1.5 Módulos, paquetes y namespaces": ut00/ut0005.md
      - "1.6 Estructuras de control": ut00/ut0006.md
      - "1.7 Tipos de datos complejos": ut00/ut0007.md
      - "1.8 Funciones": ut00/ut0008.md
      - "1.9 Errores y excepciones": ut00/ut0009.md
      - "1.10 Ficheros": ut00/ut0010.md
  - "UD2 — Xarxes Locals":
      - "📘 UD2 Completa (1 pàgina)": ut01/index.md
      - "2.1 Introducción a las redes locales": ut01/ut0101.md
      - "2.2 Mapa físico y lógico": ut01/ut0102.md
      - "2.3 Arquitecturas de red": ut01/ut0103.md
      - "2.4 MODELO OSI": ut01/ut0104.md
      - "2.5 MODELO TCP/IP": ut01/ut0105.md
      - "2.6 Tipos de cableado": ut01/ut0106.md
  - "UD3 — Págines Web":
      - "📘 UD3 Completa (1 pàgina)": ut02/index.md
      - "3.1 CheatSheet HTML5": ut02/ut0201.md
      - "3.2 CheatSheet CSS3": ut02/ut0202.md
  - "UD4 — Seguridad":
      - "📘 UD4 Completa (1 pàgina)": ut03/index.md
      - "4.1 Continguts i Recursos": ut03/ut0301.md
