site_name: "🔐 Programació, Xarxes i Sistemes Informàtics II — 2n Batxillerat"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Introducció a Python":
      - "📘 UD1 Completa (1 pàgina)": ./ut01/index.md
      - "1.1 Introducció a Python": ./ut01/ut0101.md
      - "1.2 Elementos de un programa": ./ut01/ut0102.md
      - "1.3 Tipos de datos": ./ut01/ut0103.md
      - "1.4 Funciones integradas": ./ut01/ut0104.md
      - "1.5 Módulos, paquetes y namespaces": ./ut01/ut0105.md
      - "1.6 Estructuras de control": ./ut01/ut0106.md
      - "1.7 Tipos de datos complejos": ./ut01/ut0107.md
      - "1.8 Funciones": ./ut01/ut0108.md
      - "1.9 Errores y excepciones": ./ut01/ut0109.md
      - "1.10 Ficheros": ./ut01/ut0110.md
  - "UD2 — Xarxes Locals":
      - "📘 UD2 Completa (1 pàgina)": ./ut02/index.md
      - "2.1 Introducción a las redes locales": ./ut02/ut0201.md
      - "2.2 Mapa físico y lógico": ./ut02/ut0202.md
      - "2.3 Arquitecturas de red": ./ut02/ut0203.md
      - "2.4 MODELO OSI": ./ut02/ut0204.md
      - "2.5 MODELO TCP/IP": ./ut02/ut0205.md
      - "2.6 Tipos de cableado": ./ut02/ut0206.md
  - "UD3 — Págines Web":
      - "📘 UD3 Completa (1 pàgina)": ./ut03/index.md
      - "3.1 CheatSheet HTML5": ./ut03/ut0301.md
      - "3.2 CheatSheet CSS3": ./ut03/ut0302.md
  - "UD4 — Seguridad":
      - "📘 UD4 Completa (1 pàgina)": ./ut04/index.md
      - "4.1 Continguts Teòrics i Recursos": ./ut04/ut0401.md
