site_name: "🚀 Desplegament d'Aplicacions Web — 2n DAW · Grau Superior"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Serveis de Xarxa Implicats en el Desplegament (DNS i LDAP)":
      - "📘 UD1 Completa (1 pàgina)": ut11/index.md
      - "11.1 UT 1.3 Preparación del servidor de directorios L": ut11/ut1101.md
      - "11.2 UT 1.2 Servicio de directorios LDAP": ut11/ut1102.md
      - "11.3 UT 1.1 Servicios de Red": ut11/ut1103.md
  - "UD2 — Administració de Servidors de Transferència d'Arxius (FTP / SFTP)":
      - "📘 UD2 Completa (1 pàgina)": ut10/index.md
      - "10.1 UT 2.2 Introducció - Creació servidor FTP amb SF": ut10/ut1001.md
      - "10.2 UT 2.1 Introducció - Creació servidor FTP amb VS": ut10/ut1002.md
      - "✍️ Activitats pràctiques UT10": ut10/ut10actividades.md
  - "UD3 — Arquitectures Web i Servidors d'Aplicacions":
      - "📘 UD3 Completa (1 pàgina)": ut09/index.md
      - "9.1 UT 3.4 Arquitectures web": ut09/ut0901.md
      - "9.2 UT 3.3 Arquitectures web": ut09/ut0902.md
      - "9.3 UT 3.2 Arquitectures web": ut09/ut0903.md
      - "9.4 UT 3.1 Arquitectures web": ut09/ut0904.md
      - "✍️ Activitats pràctiques UT9": ut09/ut09actividades.md
  - "UD4 — Administració i Segurització de Servidors Web":
      - "📘 UD4 Completa (1 pàgina)": ut08/index.md
      - "8.1 UT 4.2 Administració de servidors web - Seguritz": ut08/ut0801.md
      - "8.2 UT 4.1 Administració de servidors web - Instal·l": ut08/ut0802.md
      - "✍️ Activitats pràctiques UT8": ut08/ut08actividades.md
  - "UD5 — Documentació i Control de Versions (Git, GitHub, Javadoc, phpDocumentor)":
      - "📘 UD5 Completa (1 pàgina)": ut07/index.md
      - "7.1 UT 5.4 Documentació i control de versions - GitH": ut07/ut0701.md
      - "7.2 UT 5.3 Documentació i control de versions - Git": ut07/ut0702.md
      - "7.3 UT 5.2 Documentació i control de versions - phpD": ut07/ut0703.md
      - "7.4 UT 5.1 Documentació i control de versions - Java": ut07/ut0704.md
      - "✍️ Activitats pràctiques UT7": ut07/ut07actividades.md
  - "📂 Índex de Documents i Recursos": references.md
