theme: jekyll-theme-cayman
title: Portal Docent de Pepe Cuenca
description: Documentació tècnica, apunts i recursos dels mòduls de Formació Professional - Pepe Cuenca
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
