site_name: "📲 Programació, IA i Robòtica II: App Inventor i Robòtica — 3r ESO"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UT0 — Unitat Didàctica 0":
      - "📘 UT0 Completa (1 pàgina)": ut00/index.md
      - "✍️ Activitats pràctiques UT0": ut00/ut00actividades.md
  - "UT1 — App Inventor":
      - "📘 UT1 Completa (1 pàgina)": ut01/index.md
      - "1.1 Projecte final 2a Avaluació": ut01/ut0101.md
      - "✍️ Activitats pràctiques UT1": ut01/ut01actividades.md
  - "UT2 — Robòtica":
      - "📘 UT2 Completa (1 pàgina)": ut02/index.md
      - "2.1 Continguts i Recursos": ut02/ut0201.md
      - "✍️ Activitats pràctiques UT2": ut02/ut02actividades.md
  - "📂 Índex de Documents i Recursos": references.md
