site_name: "📲 Programació, IA i Robòtica II: App Inventor i Robòtica — 3r ESO"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — App Inventor":
      - "📘 UD1 Completa (1 pàgina)": ./ut01/index.md
      - "1.1 Disseny d'interfície, components i programació per blocs": ./ut01/ut0101.md
  - "UD2 — Robòtica":
      - "📘 UD2 Completa (1 pàgina)": ./ut02/index.md
      - "2.1 Continguts Teòrics i Recursos": ./ut02/ut0201.md
