site_name: "🕸️ Disseny Web amb HTML5, CSS i WordPress — 4t ESO"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UT1 — HTML":
      - "📘 UT1 Completa (1 pàgina)": ut01/index.md
      - "1.1 Sessio 1": ut01/ut0101.md
      - "1.2 1_Introducción": ut01/ut0102.md
      - "1.3 Act1_Solución": ut01/ut0103.md
      - "1.4 2_Estructura básica": ut01/ut0104.md
      - "1.5 Act2_Solución": ut01/ut0105.md
      - "1.6 3_Etiquetas para estructurar el texto": ut01/ut0106.md
      - "1.7 Act3_Solución": ut01/ut0107.md
      - "1.8 4_Etiquetas básicas de marcado": ut01/ut0108.md
      - "1.9 Act4_Sol": ut01/ut0109.md
      - "1.10 5_listas": ut01/ut0110.md
      - "1.11 6_enlaces": ut01/ut0111.md
      - "1.12 7_Tablas": ut01/ut0112.md
      - "1.13 8_Formularios": ut01/ut0113.md
      - "✍️ Activitats pràctiques UT1": ut01/ut01actividades.md
  - "UT2 — WORDPRESS":
      - "📘 UT2 Completa (1 pàgina)": ut02/index.md
      - "2.1 Continguts i Recursos": ut02/ut0201.md
  - "UT3 — Alan Turing":
      - "📘 UT3 Completa (1 pàgina)": ut03/index.md
      - "✍️ Activitats pràctiques UT3": ut03/ut03actividades.md
  - "📂 Índex de Documents i Recursos": references.md
