site_name: "🤖 Programació, IA i Robòtica I — 2n ESO"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Scratch":
      - "📘 UD1 Completa (1 pàgina)": ./ut01/index.md
      - "1.1 Continguts Teòrics i Recursos": ./ut01/ut0101.md
  - "UD2 — Robòtica":
      - "📘 UD2 Completa (1 pàgina)": ./ut02/index.md
      - "2.1 Continguts Teòrics i Recursos": ./ut02/ut0201.md
