site_name: "📊 Aplicacions Ofimàtiques — 1r SMX · Grau Mitjà"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Processador de text (I)":
      - "📘 UD1 Completa (1 pàgina)": ut02/index.md
      - "1.1 Tema 0. Suites Ofimàtiques": ut02/ut0201.md
      - "1.2 Tema 0. Writer": ut02/ut0202.md
      - "1.3 Mapa conceptual WRITER": ut02/ut0203.md
      - "1.4 Tema 2. Taules": ut02/ut0208.md
      - "1.5 Tema 3. IMATGES": ut02/ut0210.md
      - "1.6 Exemple Numeració i Vinyetes": ut02/ut0217.md
      - "1.7 curiosidades en Writer": ut02/ut0218.md
  - "UD2 — Processador de text (II)":
      - "📘 UD2 Completa (1 pàgina)": ut03/index.md
      - "2.1 Tema 7. COMBINAR CORRESPONDENCIA": ut03/ut0303.md
      - "2.2 Exemple Combinar correspondència": ut03/ut0304.md
      - "2.3 Tema 9. PLANTILLES": ut03/ut0309.md
  - "UD3 — Processador de text (III)":
      - "📘 UD3 Completa (1 pàgina)": ut04/index.md
      - "3.1 Tema 11. Index de continguts, figures i alfabèti": ut04/ut0402.md
      - "3.2 Tema 13. Treballar amb documents llargs": ut04/ut0407.md
  - "UD4 — Calc Mòdul 1 (I)":
      - "📘 UD4 Completa (1 pàgina)": ut06/index.md
      - "4.1 Manual bàsic CALC": ut06/ut0601.md
  - "UD5 — BDA. SISTEMES GESTORS BASE DE DADES (SGBD)":
      - "📘 UD5 Completa (1 pàgina)": ut12/index.md
      - "5.1 Tema 0. Introducció a les base de dades.": ut12/ut1201.md
      - "5.2 Tema 1. Sistemas Gestores de Base de Datos (vers": ut12/ut1202.md
  - "UD6 — BDA. Model ENTITAT-RELACIÓ (E-R) (Primera part)":
      - "📘 UD6 Completa (1 pàgina)": ut13/index.md
      - "6.1 Exemple_inicial_Classe_ER": ut13/ut1301.md
      - "6.2 Tema 2. Model Entitat-Relació (COMPLET)": ut13/ut1302.md
      - "6.3 Tema 2. Model Entitat-Relació (RESUMEN)": ut13/ut1303.md
  - "UD7 — BDA. Model RELACIONAL (Segona part)":
      - "📘 UD7 Completa (1 pàgina)": ut14/index.md
      - "7.1 Tema 2. Model Relacional (2ª part)": ut14/ut1401.md
  - "UD8 — BDA. Base de Datos. TAULES":
      - "📘 UD8 Completa (1 pàgina)": ut15/index.md
      - "8.1 Tema 3. TAULES ACCESS": ut15/ut1501.md
      - "8.2 Tema 3. Integridad Referencial": ut15/ut1502.md
      - "8.3 DEFINICION Mascara entrada_Regla validación": ut15/ut1503.md
      - "8.4 Ejemplos reglas de validación": ut15/ut1504.md
  - "UD9 — BDA. Base de Datos. CONSULTES":
      - "📘 UD9 Completa (1 pàgina)": ut16/index.md
      - "9.1 Tema 4. CONSULTES": ut16/ut1601.md
      - "9.2 RESUMEN CONSULTES": ut16/ut1602.md
  - "UD10 — BDA. Base de Datos. FORMULARIS":
      - "📘 UD10 Completa (1 pàgina)": ut17/index.md
      - "10.1 Tema 5. FORMULARIS": ut17/ut1701.md
  - "UD11 — BDA. Base de Datos. INFORMES":
      - "📘 UD11 Completa (1 pàgina)": ut18/index.md
      - "11.1 Tema 6. INFORMES": ut18/ut1801.md
  - "UD12 — BDA. Base de Datos. MACROS":
      - "📘 UD12 Completa (1 pàgina)": ut19/index.md
      - "12.1 Tema 7. MACROS": ut19/ut1901.md
      - "12.2 Abrir Form sin Abrir Access": ut19/ut1902.md
  - "UD13 — GIMP":
      - "📘 UD13 Completa (1 pàgina)": ut22/index.md
      - "13.1 Tema 1: Imatge Digital": ut22/ut2201.md
      - "13.2 Tema 2. Imatge vectorial (Inkscape)": ut22/ut2202.md
