site_name: "🐘 Desenvolupament Web en Entorn Servidor (PHP i Laravel) — 2n DAW · Grau Superior"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Server-side development":
      - "📘 UD1 Completa (1 pàgina)": ut01/index.md
      - "1.1 U1 Server-Side Development": ut01/ut0101.md
      - "1.2 Git Recap": ut01/ut0102.md
      - "1.3 Git Cheat Sheet": ut01/ut0103.md
  - "UD2 — Basic PHP":
      - "📘 UD2 Completa (1 pàgina)": ut02/index.md
      - "2.1 U2 Basic PHP": ut02/ut0201.md
  - "UD3 — Advanced PHP":
      - "📘 UD3 Completa (1 pàgina)": ut03/index.md
      - "3.1 U3 Advanced PHP": ut03/ut0301.md
  - "UD4 — Data access":
      - "📘 UD4 Completa (1 pàgina)": ut04/index.md
      - "4.1 U4 Data Access": ut04/ut0401.md
  - "UD5 — Introduction to frameworks. Laravel I":
      - "📘 UD5 Completa (1 pàgina)": ut05/index.md
      - "5.1 Frameworks. Laravel I": ut05/ut0501.md
      - "5.2 How to install npm (node) into our existing cont": ut05/ut0502.md
  - "UD6 — Laravel II":
      - "📘 UD6 Completa (1 pàgina)": ut06/index.md
      - "6.1 Frameworks. Laravel II": ut06/ut0601.md
      - "6.2 How to use Tailwind CSS into a Laravel project": ut06/ut0602.md
      - "6.3 How to clone a Laravel project from Github": ut06/ut0603.md
  - "UD7 — Web Services":
      - "📘 UD7 Completa (1 pàgina)": ut07/index.md
      - "7.1 Web Services": ut07/ut0701.md
  - "UD8 — Hybrid Applications":
      - "📘 UD8 Completa (1 pàgina)": ut08/index.md
      - "8.1 Hybrid applications": ut08/ut0801.md
