site_name: "⚙️ Entorns de Desenvolupament — 1r DAW / DAM · Grau Superior"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Introducción al desarrollo de software":
      - "📘 UD1 Completa (1 pàgina)": ut00/index.md
      - "1.1 Intr. al desarrollo de SW": ut00/ut0001.md
      - "1.2 Especificaciones requisitos IEEE380_ejemplo": ut00/ut0002.md
      - "1.3 Especificaciones requisitos software_ejemplo": ut00/ut0003.md
  - "UD2 — IDE's y estilo de programación":
      - "📘 UD2 Completa (1 pàgina)": ut01/index.md
      - "2.1 IDEs. Estilos de programación": ut01/ut0101.md
  - "UD3 — Control de versiones":
      - "📘 UD3 Completa (1 pàgina)": ut02/index.md
      - "3.1 Control de versiones": ut02/ut0201.md
      - "3.2 Git Cheat Sheet": ut02/ut0202.md
      - "3.3 Crear alias para log con ramas": ut02/ut0203.md
  - "UD4 — Debugging y testing":
      - "📘 UD4 Completa (1 pàgina)": ut03/index.md
      - "4.1 Debugging y testing": ut03/ut0301.md
  - "UD5 — Diagramas de clase":
      - "📘 UD5 Completa (1 pàgina)": ut04/index.md
      - "5.1 Diagramas de clase": ut04/ut0401.md
  - "UD6 — Diagramas de comportamiento":
      - "📘 UD6 Completa (1 pàgina)": ut05/index.md
      - "6.1 Diagramas de casos de uso": ut05/ut0501.md
      - "6.2 Diagramas de estado": ut05/ut0502.md
  - "UD7 — Refactorización, optimización y documentación":
      - "📘 UD7 Completa (1 pàgina)": ut06/index.md
      - "7.1 Refactorización": ut06/ut0601.md
      - "7.2 Documentación": ut06/ut0602.md
  - "UD8 — Metodologías ágiles":
      - "📘 UD8 Completa (1 pàgina)": ut07/index.md
      - "8.1 Metodologías ágiles": ut07/ut0701.md
      - "8.2 Planificación de proyectos": ut07/ut0702.md
      - "8.3 Poker planning": ut07/ut0703.md
