site_name: "⚙️ Entorns de Desenvolupament — 1r DAW / DAM · Grau Superior"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UT0 — Introducción al desarrollo de software":
      - "📘 UT0 Completa (1 pàgina)": ut00/index.md
      - "0.1 U1 - Intr. al desarrollo de SW": ut00/ut0001.md
      - "0.2 Especificaciones requisitos IEEE380_ejemplo": ut00/ut0002.md
      - "0.3 Especificaciones requisitos software_ejemplo": ut00/ut0003.md
      - "✍️ Activitats pràctiques UT0": ut00/ut00actividades.md
  - "UT1 — IDE's y estilo de programación":
      - "📘 UT1 Completa (1 pàgina)": ut01/index.md
      - "1.1 U2 - IDEs. Estilos de programación": ut01/ut0101.md
      - "✍️ Activitats pràctiques UT1": ut01/ut01actividades.md
  - "UT2 — Control de versiones":
      - "📘 UT2 Completa (1 pàgina)": ut02/index.md
      - "2.1 U3 - Control de versiones": ut02/ut0201.md
      - "2.2 Git Cheat Sheet": ut02/ut0202.md
      - "2.3 Crear alias para log con ramas": ut02/ut0203.md
      - "2.4 Material-Heroes": ut02/ut0204.md
      - "2.5 Actividades de clase": ut02/ut0205.md
      - "✍️ Activitats pràctiques UT2": ut02/ut02actividades.md
  - "UT3 — Debugging y testing":
      - "📘 UT3 Completa (1 pàgina)": ut03/index.md
      - "3.1 U4 - Debugging y testing": ut03/ut0301.md
      - "3.2 EjercicioGrafo2": ut03/ut0302.md
      - "3.3 EjercicioGrafo3": ut03/ut0303.md
      - "3.4 Códigos debugging": ut03/ut0304.md
      - "✍️ Activitats pràctiques UT3": ut03/ut03actividades.md
  - "UT4 — Diagramas de clase":
      - "📘 UT4 Completa (1 pàgina)": ut04/index.md
      - "4.1 U5 - Diagramas de clase": ut04/ut0401.md
      - "4.2 U5 - Diagramas de clase profe": ut04/ut0402.md
      - "4.3 Actividades de clase": ut04/ut0403.md
      - "✍️ Activitats pràctiques UT4": ut04/ut04actividades.md
  - "UT5 — Diagramas de comportamiento":
      - "📘 UT5 Completa (1 pàgina)": ut05/index.md
      - "5.1 Diagramas de casos de uso": ut05/ut0501.md
      - "5.2 U6.2 - Diagramas de estado": ut05/ut0502.md
      - "5.3 Actividades de clase": ut05/ut0503.md
      - "✍️ Activitats pràctiques UT5": ut05/ut05actividades.md
  - "UT6 — Refactorización, optimización y documentación":
      - "📘 UT6 Completa (1 pàgina)": ut06/index.md
      - "6.1 U7. Refactorización": ut06/ut0601.md
      - "6.2 U7.2 - Documentación": ut06/ut0602.md
      - "✍️ Activitats pràctiques UT6": ut06/ut06actividades.md
  - "UT7 — Metodologías ágiles":
      - "📘 UT7 Completa (1 pàgina)": ut07/index.md
      - "7.1 U8. Metodologías ágiles": ut07/ut0701.md
      - "7.2 U8.1 - Planificación de proyectos": ut07/ut0702.md
      - "7.3 Poker planning": ut07/ut0703.md
      - "✍️ Activitats pràctiques UT7": ut07/ut07actividades.md
  - "📂 Índex de Documents i Recursos": references.md
