site_name: "🛡️ Seguretat Informàtica — 2n SMX · Grau Mitjà"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Conceptes sobre seguretat informàtica":
      - "📘 UD1 Completa (1 pàgina)": ut01/index.md
      - "1.1 Continguts i Recursos": ut01/ut0101.md
  - "UD2 — Criptografia":
      - "📘 UD2 Completa (1 pàgina)": ut02/index.md
      - "2.1 Continguts i Recursos": ut02/ut0201.md
  - "UD3 — Seguretat passiva: Equips":
      - "📘 UD3 Completa (1 pàgina)": ut03/index.md
      - "3.1 PDF: Consum i sel·lecció de SAI": ut03/ut0301.md
  - "UD4 — Seguretat passiva: Emmagatzemament":
      - "📘 UD4 Completa (1 pàgina)": ut04/index.md
      - "4.1 Continguts i Casos Guiats": ut04/ut04actividades.md
  - "UD5 — Seguretat activa: sistema operatiu i aplicacions":
      - "📘 UD5 Completa (1 pàgina)": ut05/index.md
      - "5.1 Continguts i Casos Guiats": ut05/ut05actividades.md
  - "UD6 — Seguretat activa: Accés a xarxes":
      - "📘 UD6 Completa (1 pàgina)": ut06/index.md
      - "6.1 Continguts i Casos Guiats": ut06/ut06actividades.md
  - "UD7 — Seguretat activa: Control de xarxes":
      - "📘 UD7 Completa (1 pàgina)": ut07/index.md
      - "7.1 Continguts i Casos Guiats": ut07/ut07actividades.md
  - "UD8 — Atacs i contramesures":
      - "📘 UD8 Completa (1 pàgina)": ut08/index.md
      - "8.1 Continguts i Casos Guiats": ut08/ut08actividades.md
