site_name: "🖧 Xarxes Locals — 1r SMX · Grau Mitjà"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — Unitat Didàctica 1":
      - "📘 UD1 Completa (1 pàgina)": ut01/index.md
      - "1.1 Continguts i Recursos": ut01/ut0101.md
  - "UD2 — Unitat Didàctica 2":
      - "📘 UD2 Completa (1 pàgina)": ut04/index.md
      - "2.1 Continguts i Recursos": ut04/ut0401.md
  - "UD3 — i 6":
      - "📘 UD3 Completa (1 pàgina)": ut05/index.md
      - "3.1 Continguts i Recursos": ut05/ut0501.md
