site_name: "📱 Taller de Relacions Digitals Responsables — 1r ESO"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UT1 — L'ordinador i els seus components i els sistemes operatius":
      - "📘 UT1 Completa (1 pàgina)": ut01/index.md
      - "1.1 UD1 - L'ordinador i els seus components": ut01/ut0101.md
      - "1.2 Comportament i bon ús de les tecnologies": ut01/ut0102.md
      - "1.3 UD2. Sistemes operatius": ut01/ut0103.md
      - "✍️ Activitats pràctiques UT1": ut01/ut01actividades.md
  - "UT2 — WRITER":
      - "📘 UT2 Completa (1 pàgina)": ut02/index.md
      - "2.1 Continguts i Recursos": ut02/ut0201.md
      - "✍️ Activitats pràctiques UT2": ut02/ut02actividades.md
  - "UT3 — DRAW":
      - "📘 UT3 Completa (1 pàgina)": ut03/index.md
      - "3.1 Continguts i Recursos": ut03/ut0301.md
      - "✍️ Activitats pràctiques UT3": ut03/ut03actividades.md
  - "UT4 — INTERNET":
      - "📘 UT4 Completa (1 pàgina)": ut04/index.md
      - "4.1 Continguts i Recursos": ut04/ut0401.md
      - "✍️ Activitats pràctiques UT4": ut04/ut04actividades.md
  - "UT5 — Programació Visual amb Scratch":
      - "📘 UT5 Completa (1 pàgina)": ut05/index.md
      - "5.1 Continguts i Recursos": ut05/ut0501.md
      - "✍️ Activitats pràctiques UT5": ut05/ut05actividades.md
  - "UT6 — PRÀCTICA MECANOGRAFIA":
      - "📘 UT6 Completa (1 pàgina)": ut06/index.md
      - "6.1 Continguts i Recursos": ut06/ut0601.md
      - "✍️ Activitats pràctiques UT6": ut06/ut06actividades.md
  - "UT7 — SCRATCH BÁSICO":
      - "📘 UT7 Completa (1 pàgina)": ut07/index.md
      - "7.1 Continguts i Recursos": ut07/ut0701.md
      - "✍️ Activitats pràctiques UT7": ut07/ut07actividades.md
  - "📂 Índex de Documents i Recursos": references.md
