site_name: "📱 Taller de Relacions Digitals Responsables — 1r ESO"
theme:
  name: material
  language: ca
nav:
  - Inici: index.md
  - "UD1 — L'ordinador i els seus components i els sistemes operatius":
      - "📘 UD1 Completa (1 pàgina)": ut01/index.md
      - "1.1 L'ordinador i els seus components": ut01/ut0101.md
      - "1.2 Comportament i bon ús de les tecnologies": ut01/ut0102.md
      - "1.3 Sistemes operatius": ut01/ut0103.md
  - "UD2 — WRITER":
      - "📘 UD2 Completa (1 pàgina)": ut02/index.md
      - "2.1 Continguts i Recursos": ut02/ut0201.md
  - "UD3 — DRAW":
      - "📘 UD3 Completa (1 pàgina)": ut03/index.md
      - "3.1 Continguts i Recursos": ut03/ut0301.md
  - "UD4 — INTERNET":
      - "📘 UD4 Completa (1 pàgina)": ut04/index.md
      - "4.1 Continguts i Recursos": ut04/ut0401.md
  - "UD5 — Programació Visual amb Scratch":
      - "📘 UD5 Completa (1 pàgina)": ut05/index.md
      - "5.1 Continguts i Recursos": ut05/ut0501.md
  - "UD6 — SCRATCH BÁSICO":
      - "📘 UD6 Completa (1 pàgina)": ut07/index.md
      - "6.1 Continguts i Recursos": ut07/ut0701.md
